server:
  port: 8080
spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

jwt:
  secret: nac-korea-secret-key-must-be-at-least-256bits-long-for-hs256
  expiration: 86400000


# 주석 테스트