
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nac_korea?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: nac_user
    password: nackorea1231

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.nackorea: INFO
    root: WARN
  file:
    name: /var/www/nackorea/backend/logs/nac-korea.log
  logback:
    rollingpolicy:
      file-name-pattern: /var/www/nackorea/backend/logs/nackorea.%d{yyyy-MM-dd}.log
      max-history: 2          # 2일치만 보관
      max-file-size: 100MB    # 파일당 최대 100MB
      total-size-cap: 200MB   # 전체 최대 200MB (2일 x 100MB)
      clean-history-on-start: false

# 주석 테스트